In [1]:
import numpy as np

In [3]:
inputArray = np.array([
    [1,2,3],
    [3,4,5]
])

In [4]:
inputArray

array([[1, 2, 3],
       [3, 4, 5]])

In [5]:
inputArray.shape

(2, 3)

In [8]:
np.ones(2)

array([1., 1.])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
a = np.array([2,3,4])
b = np.array([3,5,6])
np.concatenate((a,b))

array([2, 3, 4, 3, 5, 6])

In [24]:
# The reshape function can only be used when the multiplication of the the arguments of the reshape function should be equal to
# the number of columns that the ooriginal array has.

c = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
d = c.reshape(2,6)
print(d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
